
export const HARD_MOVIE_LIST = [
    {'year': '2010', 'title': 'Hello Hum Lallann Bol Rahe Hain', 'posterurl': 'https://m.media-amazon.com/images/M/MV5BMDg5ZDJiMGQtMjIxNS00MWUxLThiMTUtODVhYTY2MDRlYzU4XkEyXkFqcGdeQXVyNTA4OTgxMzk@..jpg'},
    {'year': '2007', 'title': 'Manorama: Six Feet Under', 'posterurl': 'https://m.media-amazon.com/images/M/MV5BOGNjN2M4MDItMzc3YS00ZjdiLTlhMDMtYjk0OWQzMzc1ZjRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@..jpg'},
    {'year': '2006', 'title': 'Rehguzar', 'posterurl': 'https://m.media-amazon.com/images/M/MV5BZjFiNTBjMGQtZWM0Ny00YjRiLTg1NTQtMDllN2VjZTNlMmU0XkEyXkFqcGdeQXVyMjg1ODA0ODA@..jpg'},
    {'year': '1998', 'title': 'Keemat: They Are Back', 'posterurl': 'https://m.media-amazon.com/images/M/MV5BZjE5MzJkZTAtNGViNS00M2RjLWE1MTMtMjVlMTM1NTVjZGRjXkEyXkFqcGdeQXVyODE5NzE3OTE@..jpg'},
    {'year': '2012', 'title': 'Luv Shuv Tey Chicken Khurana', 'posterurl': 'https://m.media-amazon.com/images/M/MV5BMTY2OTk3MTg2MV5BMl5BanBnXkFtZTcwNDY5MzY1OA@@..jpg'},
    {'year': '1980', 'title': 'Albert Pinto Ko Gussa Kyon Ata Hai', 'posterurl': 'https://m.media-amazon.com/images/M/MV5BZTBlYThlZWMtYjI2YS00ZjNjLThiNjktZTdkNGY3YzFhYmZiXkEyXkFqcGdeQXVyMjUxMTY3ODM@..jpg'},
    {'year': '1986', 'title': 'Andheri Raat Mein Diya Tere Haath Mein', 'posterurl': 'https://m.media-amazon.com/images/M/MV5BYjQyNzE1NTUtODFmOS00YjI4LThlMjgtYTRmYTBlZWJjMzQ4XkEyXkFqcGdeQXVyNjkwOTg4MTA@..jpg'},
    {'year': '1989', 'title': 'Salim Langde Pe Mat Ro', 'posterurl': 'https://m.media-amazon.com/images/M/MV5BMWQ2MzM3OTItMjQ4MC00MzA1LTgzYjQtYjk5YjFmOTE0N2MyXkEyXkFqcGdeQXVyMjUxMTY3ODM@..jpg'},
    {'year': '1967', 'title': 'Boond Jo Ban Gayee Moti', 'posterurl': 'https://m.media-amazon.com/images/M/MV5BNzdhYjY2MTktYmVlNS00ZDkwLWIxMzktNWFmOWY5ZmNkOGU5XkEyXkFqcGdeQXVyNDQwOTAzNw@@..jpg'},
    {'year': '1947', 'title': 'Dr. Kotnis Ki Amar Kahani', 'posterurl': 'https://m.media-amazon.com/images/M/MV5BN2NlMGUwODQtYWFkZC00ZGQwLTgxZjItMWI0Mjg3OTc1MWU2XkEyXkFqcGdeQXVyNjczMDkzOTA@..jpg'},
    {'year': '2010', 'title': 'Apartment: Rent at Your Own Risk', 'posterurl': 'https://m.media-amazon.com/images/M/MV5BNmRiNmM3NDItNDcyMi00NDNmLThhZDUtNzY4NmYwMzZmNGRhL2ltYWdlXkEyXkFqcGdeQXVyNjQ2MjQ5NzM@..jpg'},
    {'year': '2015', 'title': 'Gour Hari Dastaan: The Freedom File', 'posterurl': 'https://m.media-amazon.com/images/M/MV5BNTQ3ZDhhMzYtMWFkOS00OTQxLWFjNzMtMTkxY2Q2ZmJiZDNmXkEyXkFqcGdeQXVyODE5NzE3OTE@..jpg'},
    {'year': '1984', 'title': 'Mohan Joshi Hazir Ho!', 'posterurl': 'https://m.media-amazon.com/images/M/MV5BYWRhNjY3MTktZTJkMC00MTkyLTlmODAtYTcwOGE5ZDU3ZmQ4XkEyXkFqcGdeQXVyMjYxODMwNjk@..jpg'},
    {'year': '2017', 'title': 'Anaarkali of Aarah', 'posterurl': 'https://m.media-amazon.com/images/M/MV5BNWZhMWRlYmUtNjAyYS00N2E1LTk3MjMtMDYxZDczNjdhODI5XkEyXkFqcGdeQXVyODE5NzE3OTE@..jpg'},
    {'year': '2017', 'title': 'Laali Ki Shaadi Mein Laaddoo Deewana', 'posterurl': 'https://m.media-amazon.com/images/M/MV5BNzBhYzQzMTItYTQ1My00OWFiLWI0ZDEtM2ZkYjQ3NzFlNzQxXkEyXkFqcGdeQXVyNTExMzQ3MA@@..jpg'},
    {'year': '1977', 'title': 'Dulhan Wahi Jo Piya Man Bhaaye', 'posterurl': 'https://m.media-amazon.com/images/M/MV5BYTQ5ZmJiMmYtNTAwZC00YTVhLWEyMDYtYTU5YzM1MjIyNWFkXkEyXkFqcGdeQXVyMTUxODIyNzk@..jpg'},
    {'year': '1984', 'title': 'Aaj Kaa M.L.A. Ram Avtar', 'posterurl': 'https://m.media-amazon.com/images/M/MV5BNGZlNzRmYjUtN2FiYy00NzM4LTk3NTAtZjljYzNjMjgzNmRlXkEyXkFqcGdeQXVyODE5NzE3OTE@..jpg'},
    {'year': '1990', 'title': 'Thodasa Roomani Ho Jaayen', 'posterurl': 'https://m.media-amazon.com/images/M/MV5BZDg2MzNjYzEtYmI1NC00NWM0LThlNDUtMTQ1MGQ1NjNhMzg5XkEyXkFqcGdeQXVyNDUzOTQ5MjY@..jpg'},
    {'year': '1960', 'title': 'Zimbo Shaher Mein', 'posterurl': 'https://m.media-amazon.com/images/M/MV5BZDMxNDUxOTMtMjQ0MC00OGM4LTk1NjItYWRjODgyOWMxNjZkXkEyXkFqcGdeQXVyNDE5MTU2MDE@..jpg'},
    {'year': '2018', 'title': 'Lashtam Pashtam', 'posterurl': 'https://m.media-amazon.com/images/M/MV5BNDc2Y2U2NDMtZTFkNC00OTIxLTliODMtN2IzODY5NDdiNjIxXkEyXkFqcGdeQXVyODE5NzE3OTE@..jpg'},
    {'year': '1981', 'title': 'Guru Suleman Chela Pahelwan', 'posterurl': 'https://m.media-amazon.com/images/M/MV5BNDc3NTgxMGItZmFkYS00YmZmLWEzNjktY2NlZTA3YjUxMjAwXkEyXkFqcGdeQXVyNTM3MDMyMDQ@..jpg'},
    {'year': '1979', 'title': 'Do Ladke Dono Kadke', 'posterurl': 'https://m.media-amazon.com/images/M/MV5BMjYzMjA2NDMtODJjNy00YzQ0LWFmMjktNDRiNmQ0MjViZjBhXkEyXkFqcGdeQXVyMzU0NzkwMDg@..jpg'},
    {'year': '1988', 'title': 'Paap Ko Jalaa Kar Raakh Kar Doonga', 'posterurl': 'https://m.media-amazon.com/images/M/MV5BMTNjOTlmNDUtY2U1ZC00MDU1LWE0YjYtZDM1MjNmYTRmZWFmXkEyXkFqcGdeQXVyODE5NzE3OTE@..jpg'},
    {'year': '1975', 'title': 'Dhoti Lota Aur Chowpatty', 'posterurl': 'https://m.media-amazon.com/images/M/MV5BOGYzYjVkM2MtZTZhMC00OGY1LTg2Y2UtMmZlNGI0ZDU1ZmZjXkEyXkFqcGdeQXVyODE5NzE3OTE@..jpg'},
    {'year': '1978', 'title': 'Arvind Desai Ki Ajeeb Dastaan', 'posterurl': 'https://m.media-amazon.com/images/M/MV5BNTVhZjM3MGYtN2Q2Yy00OGI0LWEwNmItNWUwZGMwMmZjZWIwXkEyXkFqcGdeQXVyMjUxMTY3ODM@..jpg'},
    {'year': '1971', 'title': 'Jal Bin Machhli Nritya Bin Bijli', 'posterurl': 'https://m.media-amazon.com/images/M/MV5BZGE4OTBiOWUtY2Q0Mi00MDk0LWE1NjItMGZhMzg1YzMzNGU0XkEyXkFqcGdeQXVyNjkwOTg4MTA@..jpg'},
    {'year': '1974', 'title': 'Badhti Ka Naam Dadhi', 'posterurl': 'https://m.media-amazon.com/images/M/MV5BZjI5YTdlOWUtZDA4NC00NDY3LThmODktOTNlZjRhMmU0ZjY2XkEyXkFqcGdeQXVyMjU4NDY1ODA@..jpg'},
    {'year': '1991', 'title': 'Mehandi Ban Gai Khoon', 'posterurl': 'https://m.media-amazon.com/images/M/MV5BNDI4ZWRkYWEtNmY0Yi00NzViLTk4MTYtZjdiYmQ4NGE4NDU2XkEyXkFqcGdeQXVyODE5NzE3OTE@..jpg'},
    {'year': '2005', 'title': 'Maine Gandhi Ko Nahin Mara', 'posterurl': 'https://m.media-amazon.com/images/M/MV5BY2Q4MDIzOTctZTc2OC00MTFjLWEyOGYtNDI3MTc0ZDBkYjUxXkEyXkFqcGdeQXVyNDUzOTQ5MjY@..jpg'},
    {'year': '1989', 'title': 'Bandook Dahej Ke Seenay Par', 'posterurl': 'https://m.media-amazon.com/images/M/MV5BYmFhODgxNjYtNjRmYy00ZDJhLWIwNmYtODliODNjYzkwNmY5XkEyXkFqcGdeQXVyODE5NzE3OTE@..jpg'},
    {'year': '2019', 'title': 'Lakhmipur ke Lukkhe', 'posterurl': 'https://m.media-amazon.com/images/M/MV5BZmY4MTg0YjAtYmRmNS00ZTBhLWFjY2YtMzYwNWFjMDgwOTE3XkEyXkFqcGdeQXVyNjU2NDgyMzA@..jpg'},
    {'year': '2019', 'title': 'Modi karma and me', 'posterurl': 'https://m.media-amazon.com/images/M/MV5BZWM1Yjg2NDEtNjRkMy00NjYxLTkxNWItZjE1N2I3OWJlYTVhXkEyXkFqcGdeQXVyMzA5OTY0MjY@..jpg'},
]